### ISSUE TITLE
在Xcode15中，运行Demo会崩溃在NWProtocolTCP.Options()

### ISSUE THREAD

**Issue by liufenghuanwu** [MetaMask/metamask-ios-sdk#110]
In XCODE15, I run the Example project directly in the SDK, which will collapse in nwprotocoltcp.options (). The following figure can be seen, hoping to have a solution.
![POPO20231127-102308](https://github.com/MetaMask/metamask-ios-sdk/assets/13494579/7242a85e-bb68-4bfd-b443-44494ed9a625)

**Comment by elefantel** [comment]
@liufenghuanwu try deleting `Example/Pods` and `Example/Podfile.lock` and then do `pod install`. It's the StarScream version that is incompatible with Xcode 15 and doing pod install should update it.

**Comment by liufenghuanwu** [comment]
> @liufenghuanwu try deleting `Example/Pods` and `Example/Podfile.lock` and then do `pod install`. It's the StarScream version that is incompatible with Xcode 15 and doing pod install should update it.

I tried following your suggestion, but it still crashes. I have modified it myself and it can run without crashing. I have submitted a PR. Could you please check if the relevant modifications are acceptable? Thank you.

**Comment by christopherferreira9** [comment]
Hi all! We have included @liufenghuanwu 's changes in the last release and this should be fixed there. The version is `0.4.0`.
