### ISSUE TITLE
Manifest 'swiftLanguageVersions' invalid version

### ISSUE THREAD

**Issue by tom-demartino** [MetaMask/metamask-ios-sdk#132]
I tried following the instructions for [installing the SDK via SPM](https://docs.metamask.io/wallet/how-to/use-sdk/mobile/ios/).

However SPM threw an error and was unable to resolve the dependency due to the version specified in the manifest and I was unable to import the SDK into my project.
https://github.com/MetaMask/metamask-ios-sdk/blob/d293a6cf6a19537e6887815aaaa6771372d8d5ec/Package.swift#L35

I tried compiling a small file using the [-swift-version compiler flag](https://developer.apple.com/documentation/packagedescription/swiftversion/version(_:))

```
swiftc -o app app.swift -swift-version 5.5
<unknown>:0: error: invalid value '5.5' in '-swift-version 5.5'
<unknown>:0: note: valid arguments to '-swift-version' are '4', '4.2', '5'
```

I was successfully able to install the SDK using CocoaPods, but I'd prefer to use SPM.

M1 MacBook Pro
macOS Sonoma 14.2.1
XCode 15.2
Swift compiler info:
```
Apple Swift version 5.8.1 (swiftlang-5.8.0.124.5 clang-1403.0.22.11.100)
Target: arm64-apple-darwin23.2.0
```

Please let me know if there is any other info I can provide and TIA.

**Comment by elefantel** [comment]
Hi @tom-demartino thanks for the issue.
I could successfully integrate the SDK using SPM on similar environment to yours

Mac M1 pro
macOS Sonoma 4.2.1
Xcode 15.2

Swift compiler:
Swift version 5.9.2 (swiftlang-5.9.2.2.56 clang-1500.1.0.2.5)
Target: arm64-apple-macosx14.0

However, we have dropped the version to swiftLanguageVersions: [.version("5")] in #134. Please give it a try and let us know if all good?

**Comment by tom-demartino** [comment]
@elefantel looks like that did the trick, thank you!
