### ISSUE TITLE
Subject: Issue with Approve Operation in MetaMask iOS SDK

### ISSUE THREAD

**Issue by wushiqiwu** [MetaMask/metamask-ios-sdk#173]
### Provide environment information

none

### MetaMask iOS SDK Version

0.7.3

### MetaMask Wallet Version

7.26.0

### Xcode Version

XCode 15.4

### iOS Version

17.5.1

### Describe the Bug

We need to perform an approve operation, so we called the request method in the MetaMask iOS SDK and assembled the necessary parameters for the approve data. After redirecting to MetaMask and completing the approval, we did not receive a callback result for the related method. Additionally, clicking "Return to DApp" does not properly return us to the application. Furthermore, after manually returning to the app, we are unable to receive Scheme callbacks when calling other SDK methods.

Here is the code we used:

`

func approve(spenderAddress: String, tokenAddress: String, amount: Double, completion: https://github.com/escaping (_ success: Bool, _ message: String) -> Void) {

    Task {
        // Method ID
        let approveMethodID = "0x095ea7b3"
        
        // Ensure spenderAddress has the correct length
        let paddedSpenderAddress = spenderAddress.paddedAddress()
        
        // Convert amount to the smallest unit (USDT .mwei)
        let bigAmount = BigInt(amount: amount, unit: .mwei)
        let paddedAmount = bigAmount.paddedAmount()
        
        // Build the data string
        let data = approveMethodID + paddedSpenderAddress + paddedAmount
        
        let transaction = AXTransaction(
            to: tokenAddress,
            from: metaMaskSDK.account,
            data: data
        )
        
        let parameters: [AXTransaction] = [transaction]
        
        let transactionRequest = EthereumRequest(
            method: .ethSendTransaction,
            params: parameters // eth_sendTransaction RPC call expects an array of parameters
        )
        
        let result = await self.metaMaskSDK.request(transactionRequest)

        DispatchQueue.main.async {
            switch result {
            case .success(let message):
                completion(true, message)
            case .failure(let error):
                completion(false, error.message)
            }
        }
    }
}
`

Clicking the button at the bottom does not redirect back to our app.

![FDEvbpjBio9EcxxXO8nuiUynsde](https://github.com/user-attachments/assets/ab01f64d-4f30-4dc8-b78b-4aa16dfd0f40)

### Expected Behavior

After approval, it can redirect back to my app normally.

### Steps To Reproduce

1

**Comment by christopherferreira9** [comment]
Hi @wushiqiwu are you using deeplink based communication or socket based communication?

**Comment by wushiqiwu** [comment]
> Hi @wushiqiwu are you using deeplink based communication or socket based communication?

I'm using  deeplink

**Comment by yanfj** [comment]
I encountered the same issue using deeplink; the callback isn’t triggered, and after manually returning to the app, subsequent API calls also fail to receive callbacks.

**Comment by elefantel** [comment]
Hi @wushiqiwu & @yanfj , the issue is possibly that you did not configure the url scheme in your app. The instructions to set it up are described in the README in this [section](https://github.com/MetaMask/metamask-ios-sdk?tab=readme-ov-file#option-1-deeplink-communication-layer)

Also note setup in the AppDelegate

**Comment by yanfj** [comment]
I followed the steps in the README and correctly configured the URL scheme in the app. The issue currently only occurs in the Approve method. @elefantel

**Comment by elefantel** [comment]
@yanfj @wushiqiwu I'm assuming you first call `connect()` successfully - I know this is an obvious step but just checking? Could you please share your logs?

**Comment by christopherferreira9** [comment]
Might be related to https://github.com/MetaMask/metamask-mobile/issues/10315

**Comment by yanfj** [comment]
![IMG_1251](https://github.com/user-attachments/assets/17d85d95-798a-4e54-89d4-47e84cfd0ad9)
I discovered that it was because I had enabled Smart Transactions. When I disabled this option, the Approve operation was able to quickly callback after confirmation. @christopherferreira9
