### ISSUE TITLE
MetaMask Request Popup Showing Undefined Site 

### ISSUE THREAD

**Issue by AakifFRT** [MetaMask/metamask-ios-sdk#61]
Added my dapp link in Dapp(name: "NVG8", url: "https://data.nvg8.io") but popup not showing my app name

**Comment by elefantel** [comment]
Hi @AakifFRT , thanks for the issue! Yes, the popup on MetaMask wallet should show the originating dapp, and currently it doesn't but only shows the account and the network.

We are aware of this and will be improving the experience on the MM wallet side.

Let me know if this addresses your issue in the meantime?
