### ISSUE TITLE
Metamask request pop-up ends in error state

### ISSUE THREAD

**Issue by zwolsman** [MetaMask/metamask-ios-sdk#63]
This would provide a pop-up where the user can connect their wallet (in the Metamask native app). I just discovered this isn't the case anymore. When Metamask is being opened from the iOS SDK it ends up in an error state. I did provide dapp configuration.

![screenshot](https://cdn.discordapp.com/attachments/986223701127200778/1085464019525193778/IMG_3911.png)

**Comment by cbrzn** [comment]
i am encountering the same problem when running the examples - did u find a solution?

**Comment by cbrzn** [comment]
just tested and works as expected :) feel free to close this 🙏 @andreahaku

**Comment by elefantel** [comment]
Hi @zwolsman,

Thanks for reporting the issue. We have released version 0.1.1 of the SDK which has this issue fixed. 

Please update your packages if using Swift Package Manager or your Podfile if using Cocoapods.

Thanks!
