### ISSUE TITLE
Install via Cocoapods is broken

### ISSUE THREAD

**Issue by machl** [MetaMask/metamask-ios-sdk#66]
SDK usage via Cocoapods is broken - the imported library doesn't contain any source files, only `ReplaceMe.swift` file.

Steps to reproduce:

1. Create new Xcode project
2. `pod init`
3. Add `pod 'metamask-ios-sdk'` to Podfile
4. `pod install`
5. Pod was installed without an error, but no MetaMask SDK source files were installed. See screenshot:

![Screenshot 2023-04-03 at 10 02 00](https://user-images.githubusercontent.com/3704075/229448771-6a86faaa-2a78-4740-96da-eb516cd8cf20.png)

**Comment by christopherferreira9** [comment]
Hi @machl ! This issue should be solved by now. You should be able to get the correct version with `pod install --repo-update`. Let us know if you managed to make it work.

**Comment by vincentiss** [comment]
same issue still for me...
