### ISSUE TITLE
How to use USDT to initiate transactions? 

### ISSUE THREAD

**Issue by echobool** [MetaMask/metamask-ios-sdk#69]
The package I am using is metamask-ios-sdk, and I cannot find a corresponding method to handle it.

How to use USDT to initiate transactions? There is no case found in the document, do you know? emergency

**Comment by elefantel** [comment]
Hi @echobool you can use the standard `eth_sendTransaction` call for USDT

**Comment by echobool** [comment]
> Hi @echobool you can use the standard `eth_sendTransaction` call
> 
> ```
> let parameters: [String: String] = [
>     "to": usdtContractAddress,
>     "from": yourAddress,
>     "gas": gas,
>     "gasPrice": gasPrice,
>     "nonce": nonce,
>     "data": data    
>   ]
> 
> let transactionRequest = EthereumRequest(
>     method: .ethSendTransaction,
>     params: [parameters]
>     )
> ```

I am trying to get the user to pay usdt to my project, your recipient is the usdt contract address which is not correct
