### ISSUE TITLE
Response decode bug

### ISSUE THREAD

**Issue by ekamalov** [MetaMask/metamask-ios-sdk#71]
In some cases, a decoding error occurs. 
what could this be related to?

`============
mmsdk| Error: Message ["message": BEcYPnKvkZUngF5Cu8nsSYfhCI2h25m+/VNMxV5jPGrfnQ5wdVjQu7gxd/ULdAstZy5Bf3vdCEs+q2bgac42ivhAft7gJV68kLt1e2VsAzPjOKfqYnnHzFrEJZOXuJAqQbjVCzP/agIea/2+RLcj1Jg=, "id": A6C4B77B-5F39-4FF9-A0B3-2054DD56A10C] could not be decoded: The data couldn’t be read because it isn’t in the correct format.
Func: message(from:)
File: Models.swift
Line: 49
============
`

**Comment by christopherferreira9** [comment]
Hi! Can you provide us some more information on when this happens? Is it with a specific request?

**Comment by ekamalov** [comment]
Hi @christopherferreira9, this is not related to a specific request, it appears spontaneously.

You can request ethRequestAccounts and cancel the metamake request.

**Comment by elefantel** [comment]
As noted in another conversation, this has been fixed when session persistence was merged
