### ISSUE TITLE
MetaMask App  installed, but when linking the wallet, it still jumps to the AppStore

### ISSUE THREAD

**Issue by chi-9527** [MetaMask/metamask-ios-sdk#72]
metamask iOS sdk on some iPhones, the MetaMask App has already been installed, but when linking the wallet, it still jumps to the AppStore。

the MetaMask App has already been installed

1.  ethereum.connect(dapp).
2. open safari, url is "https//metamask.app.link/"
3. then open appstore

**Comment by chi-9527** [comment]
My iPhone can wake up Metamask app, but my friend's can't，just open appstore page

**Comment by christopherferreira9** [comment]
HI @chi-9527 ! Can you and your friend check the following details?
- MetaMask version
- iOS version
- SDK version you're both using

**Comment by chi-9527** [comment]
Uninstall metamask, reinstall it, and it can be awakened again.
Maybe metamask has been upgraded and installed before, which caused the problem?

**Comment by christopherferreira9** [comment]
I'm sorry @chi-9527 , I wasn't able to get on top of this issue. Did you manage to solve it by uninstalling and installing again?

**Comment by chi-9527** [comment]
> I'm sorry @chi-9527 , I wasn't able to get on top of this issue. Did you manage to solve it by uninstalling and installing again?
yes

**Comment by chi-9527** [comment]
> I'm sorry @chi-9527 , I wasn't able to get on top of this issue. Did you manage to solve it by uninstalling and installing again?

yes
