### ISSUE TITLE
personalSign bug

### ISSUE THREAD

**Issue by ekamalov** [MetaMask/metamask-ios-sdk#73]
when I try to sign a message of such a sample:
`9f7115a3ce77b2a31d7b0d2cb7031a64da5159330e24bf1d8255316c5fe879ae`

1) incorrectly displayed
2) incorrectly signed
3) incorrectly number encoding

![IMG_9610 2](https://user-images.githubusercontent.com/16791894/235169670-28875872-d47d-4d56-833f-d5eea469ee68.PNG)

**Comment by christopherferreira9** [comment]
Hi @ekamalov ! What should that message print?
Can you try the following payload? It should show "Example `personal_sign` message"
`0x4578616d706c652060706572736f6e616c5f7369676e60206d657373616765`

**Comment by ekamalov** [comment]
Hi @christopherferreira9, for this "Example personal_sign message" text, it works fine. The problem is when we use a 64-character string of hexadecimal digits. 
for example "c2f96b514701c90eeb9f7cfc959891fb537edc5782ed54be217de45d85bebed8"

**Comment by ekamalov** [comment]
"c2f96b514701c90eeb9f7cfc959891fb537edc5782ed54be217de45d85bebed8".data(using: .utf8)!.map { String(format: "%02x", $0) }.joined()  **solution**
