### ISSUE TITLE
The request was denied by service delegate (SBMainWorkspace)

### ISSUE THREAD

**Issue by zp18862956943** [MetaMask/metamask-ios-sdk#74]
After I set the name and url of the dapp, I can get the address when I connect for the first time, but when I want to connect later, the console will report the above information "The request was denied by service delegate (SBMainWorkspace) for reason: Security ("Application XXXX(bundle id) is neither visible nor entitled, so may not perform un-trusted user actions" 。 how to slove?

**Comment by zp18862956943** [comment]
The app is version 6.3.0 of iOS downloaded from the Appstore

**Comment by christopherferreira9** [comment]
Hi @zp18862956943 can you please update the MetaMask Mobile Wallet to the most recent version available?

**Comment by christopherferreira9** [comment]
Hi @zp18862956943 . We will be closing this issue assuming the issue has been solved. Please feel free to open a new issue if the problem persists.
Thank you for reporting!
