### ISSUE TITLE
I have an issue metamask-ios-sdk. It opens AppleStore even if the app installed 

### ISSUE THREAD

**Issue by DRESSXcom** [MetaMask/metamask-ios-sdk#78]
Hi! 

I'm using the Metamask iOS SDK for our app, and we realized that sometimes, even if Metamask is installed, the example app from the rep opens the App Store instead of the Metamask app. This issue seems to occur more frequently on Max iPhones.

**Comment by christopherferreira9** [comment]
Hi @DRESSXcom !
Can you provide the following details for us to investigate?
- iOS SDK version
- MetaMask wallet version

**Comment by DRESSXcom** [comment]
Hi @christopherferreira9 
metamask-ios-sdk (0.2.0)
MetaMask wallet version (7.2.0)
https://drive.google.com/file/d/1sd2BBCQNdwMUzTlR905IoeuBdg93Ldtp/view?usp=sharing

**Comment by christopherferreira9** [comment]
That is definitely weird. I have an iPhone 13 Pro max where I can try this on. I'll get back to you once I manage to get around it.

**Comment by DRESSXcom** [comment]
@christopherferreira9  Also, on some phones, it opens the MM directly but doesn't show the connection dialog, resulting in no connection to the MM.

**Comment by christopherferreira9** [comment]
Hi @DRESSXcom can you please provide the iOS version you're using?

**Comment by nick70007** [comment]
The metamask app switches back to the app without even showing the connection prompt and then I am getting this error:

thread '' panicked at 'called Result::unwrap() on an Err value: InvalidMessage', src/lib.rs:144:38
note: run with RUST_BACKTRACE=1 environment variable to display a backtrace
libc++abi: terminating due to uncaught foreign exception

**Comment by DRESSXcom** [comment]
16.5 @christopherferreira9

**Comment by nick70007** [comment]
Hello @DRESSXcom are you facing the same issue that I am facing?

**Comment by nick70007** [comment]
I am using native swift and have integrated Metamask sdk, sometimes it doesnt show the connection prompt and redirect to the app and gives me this error

thread '' panicked at 'called Result::unwrap() on an Err value: InvalidMessage', src/lib.rs:144:38
note: run with RUST_BACKTRACE=1 environment variable to display a backtrace
libc++abi: terminating due to uncaught foreign exception

can you help me with this @DRESSXcom ?

**Comment by nick70007** [comment]
Or can you give me an example code of yours on how you have integrated, then also it will be useful

**Comment by DRESSXcom** [comment]
I have two issues. First, the SDK opens the App Store even if the MM is installed. Second, when it opens the app, there is no connection and it doesn't return me back to the app. It looks like that your case is a third type of issue. 

I run the APP example from the metamask-ios-sdk team and see this issues.

**Comment by nick70007** [comment]
Actually its not stable i guess. @DRESSXcom the team needs to look into this

**Comment by nick70007** [comment]
I am not getting the redirection to app store error, but I am getting the error once it switches from metamask to the application. So, weird. And also the connection prompt sometimes come and sometimes not

**Comment by nick70007** [comment]
> I have two issues. First, the SDK opens the App Store even if the MM is installed. Second, when it opens the app, there is no connection and it doesn't return me back to the app. It looks like that your case is a third type of issue.
> 
> I run the APP example from the metamask-ios-sdk team and see this issues.

you will be redirected to the app only when you accept the connection prompt, and for that the connection prompt is necessary

**Comment by christopherferreira9** [comment]
hi @DRESSXcom , 
When you say `Second, when it opens the app,` what is the app, MetaMask Wallet or the Example dapp?

**Comment by DRESSXcom** [comment]
@christopherferreira9 Its too issues. 
1. MM installed, but example app opens Appstore instead MM  - the first issue 
2. MM installed, from example app MM opens, but no connection dialog and it doesn't return me back to the example app - the second issue

**Comment by christopherferreira9** [comment]
Hi all! Can you please try this with the latest of the MetaMask iOS SDK (`v0.2.2`)?

**Comment by christopherferreira9** [comment]
We're closing this issue. Please feel free to open a new one if the issue still persists.
