### ISSUE TITLE
How to store session in your current example code

### ISSUE THREAD

**Issue by nick70007** [MetaMask/metamask-ios-sdk#79]
I am trying to run your code example for iOS. In your code where should I place the store session code? How to do it actually. And also, is the scanning from the QR code available in your repo?

**Comment by christopherferreira9** [comment]
Hi @nick70007 can you please provide more details about the issues you're experience? What do you mean with "store session code"?
QR code is not available through the iOS SDK.

**Comment by nick70007** [comment]
will the QR code gonna be available anytime soon? @christopherferreira9

**Comment by nick70007** [comment]
And also I have integrated your sdk into my Native Swift Code, But its not stable. Sometimes it connects and sometimes not @christopherferreira9

**Comment by christopherferreira9** [comment]
Hi @nick70007 ! We're not planing to use QRCode on the MetaMask iOS SDK for te foreseeable future but this can change at any time as we find new ways to improve the SDK.
The session is persisted automatically from v0.2.0 further. This is stored on the Dapp side through the keychain and on the MetaMask wallet side. Keep in mind that the core functionality and operation through the socket connection still remains, this means that even though the session is persisted there will always be the need to resume a said session to communicate between dapp and MetaMask.
We're working on stability fixes for the connection, stay tunned!
I'm closing this issue but feel free to open a new one if you need more assistance!
