### ISSUE TITLE
SPM error

### ISSUE THREAD

**Issue by PandaZhang530** [MetaMask/metamask-ios-sdk#81]
<img width="656" alt="image" src="https://github.com/MetaMask/metamask-ios-sdk/assets/140152146/3f387cf7-f274-46db-8d80-b991b9dd3d83">

**Comment by christopherferreira9** [comment]
Hi @PandaZhang530 ! Can you please provide us with the following details:
- Did you try adding the metamask-ios-sdk via cocoapods?
- Extra information related to the way you're trying to integrate the metamask-ios-sdk

In the mean time, can you please reset your swift packages on your xcode?

**Comment by PandaZhang530** [comment]
This was solved after I upgrade my StarScream to V4.0+
