### ISSUE TITLE
Please Update SocketIO depending on StarScream for fixing this compile error

### ISSUE THREAD

**Issue by PandaZhang530** [MetaMask/metamask-ios-sdk#83]
<img width="1111" alt="image" src="https://github.com/MetaMask/metamask-ios-sdk/assets/140152146/b0b20e36-9be4-4330-9f58-279493ebeb6a">

**Comment by christopherferreira9** [comment]
Hi @PandaZhang530 !
Can you please provide us with more details about this issue? I've just tried to create a brand new project and it seems to work with no compilation errors. Are you using the swift package manager or cocoapods?

**Comment by PandaZhang530** [comment]
Yes，of course, this error appears with cocoapods when i run your official demo with Xcode  15.0 beta 4

**Comment by christopherferreira9** [comment]
Hi @PandaZhang530 ! We are aware of issues related to Xcode 15, can you please try with the latest Xcode version (14.3)?

**Comment by PandaZhang530** [comment]
> Hi @PandaZhang530 ! We are aware of issues related to Xcode 15, can you please try with the latest Xcode version (14.3)?

I am aware of that , and my test device is running the iOS 17 beta version, so i can't use the Xcode version below 15...

**Comment by christopherferreira9** [comment]
We are just about to release a fix for the Xcode 15. We'll let you know once we do

**Comment by elefantel** [comment]
@PandaZhang530 the fix for Xcode 15 has been released. Please update to the latest version of the SDK - 0.2.1. Let us know if all good?

**Comment by PandaZhang530** [comment]
> @PandaZhang530 the fix for Xcode 15 has been released. Please update to the latest version of the SDK - 0.2.1. Let us know if all good?

Well done!!! Compile problem has been fixed~

**Comment by elefantel** [comment]
Amazing, thanks!
