### ISSUE TITLE
Please fix Connect function

### ISSUE THREAD

**Issue by RawNatural** [MetaMask/metamask-ios-sdk#91]
Hi,
    Can you guys please fix the standard connect function. It often (60% of the time) doesn't work. 
    mmsdk| SDK connected to server
    mmsdk| Clients connected: [xxxx]
    mmsdk| SDK disconnected
These are the messages it will show when it doesnt work.

    It will often disconnect the SDK before it gets a chance to connect.
    Maybe a possiblity would be to hold off on disconnecting the SDK for another 5-10 seconds until the client properly connects?
    Or try to fix whatever is causing the SDK to disconnct.
    Please, and thank you.
    a keen user...

**Comment by christopherferreira9** [comment]
Hi @RawNatural ! Are you using any sort of VPN when trying to connect?

**Comment by RawNatural** [comment]
No, i'm not using a VPN

**Comment by christopherferreira9** [comment]
Hi @RawNatural , can you share a piece of code where you make this initial connection, specially the SDK initialization?

**Comment by christopherferreira9** [comment]
Hi @RawNatural ! We're going to close this issue due to inactivity but please feel free to open a new one at any time.
