### ISSUE TITLE
Firebase crash log, SDK v0.2.2

### ISSUE THREAD

**Issue by SunZhiC** [MetaMask/metamask-ios-sdk#95]
Title: Crash when connect

Issue: Crash when connect

Observed Behavior: Occasionally, when call method MetaMaskSDK.shared.ethereum.connect

Expected Behavior: Connect metamask app successfully

Reproduction Rate: This issue has a low reproduction rate.

Steps to Reproduce:

[First step] call method MetaMaskSDK.shared.ethereum.connect

Environment:

Software Version: v0.2.2
Additional Information:

Here is the full crash log from Firebase:

Crashed: com.apple.main-thread
SIGABRT ABORT 0x00000002078f4b38

Crashed: com.apple.main-thread
0  libsystem_kernel.dylib         0x7b38 __pthread_kill + 8
1  libsystem_pthread.dylib        0x73bc pthread_kill + 268
2  libsystem_c.dylib              0x20524 abort + 168
3  libc++abi.dylib                0x11b7c __cxxabiv1::__aligned_malloc_with_fallback(unsigned long) + 130
4  libc++abi.dylib                0x18f8 demangling_terminate_handler() + 132
5  FirebaseCrashlytics            0x18688 FIRCLSTerminateHandler() + 404
6  libc++abi.dylib                0x10f18 std::__terminate(void (*)()) + 20
7  libc++abi.dylib                0x10ea0 std::terminate() + 44
8  libobjc.A.dylib                0x2d248 objc::DenseMapBase<objc::DenseMap<objc_class*, PendingInitialize*, objc::DenseMapValueInfo<PendingInitialize*>, objc::DenseMapInfo<objc_class*>, objc::detail::DenseMapPair<objc_class*, PendingInitialize*> >, objc_class*, PendingInitialize*, objc::DenseMapValueInfo<PendingInitialize*>, objc::DenseMapInfo<objc_class*>, objc::detail::DenseMapPair<objc_class*, PendingInitialize*> >::FatalCorruptHashTables(objc::detail::DenseMapPair<objc_class*, PendingInitialize*> const*, unsigned int) const + 14
9  libdispatch.dylib              0x3a44 _dispatch_client_callout + 40
10 libdispatch.dylib              0x11f48 _dispatch_main_queue_drain + 928
11 libdispatch.dylib              0x11b98 _dispatch_main_queue_callback_4CF + 44
12 CoreFoundation                 0x51800 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 16
13 CoreFoundation                 0xb704 __CFRunLoopRun + 2532
14 CoreFoundation                 0x1ebc8 CFRunLoopRunSpecific + 600
15 GraphicsServices               0x1374 GSEventRunModal + 164
16 UIKitCore                      0x514b58 -[UIApplication _run] + 1100
17 UIKitCore                      0x296090 UIApplicationMain + 364
18 libswiftUIKit.dylib            0x30ecc UIApplicationMain(_:_:_:_:) + 104
19 Demo                           0x715b4 static UIApplicationDelegate.main() + 104 (<compiler-generated>:104)
20 Demo                           0x7153c static AppDelegate.$main() + 37 (AppDelegate.swift:37)
21 Demo                           0x71fd8 main + 38 (AppDelegate.swift:38)
22 ???                            0x10734dda4 (Missing)

crash_info_entry_0 | terminating with uncaught foreign exception
-- | --
crash_info_entry_1 | abort() called

**Comment by christopherferreira9** [comment]
Hi @SunZhiC can you please provide more details about the issue you're experiencing? Could you please provide the piece of code where you're using the SDK or share a repository where we can see it?

**Comment by SunZhiC** [comment]
> Hi @SunZhiC can you please provide more details about the issue you're experiencing? Could you please provide the piece of code where you're using the SDK or share a repository where we can see it?

I think the error is caused by your [Ecies.xcframework](https://github.com/MetaMask/metamask-ios-sdk/tree/main/Sources/metamask-ios-sdk/Frameworks/Ecies.xcframework), it not a iOS native error.
We get the crash from Firebase, no more information.

**Comment by christopherferreira9** [comment]
Hi @SunZhiC ! 
This should be fixed with the latest version of the iOS SDK. Can you please try bumping to `v0.3.1`?
